# Generated by Django 4.1.2 on 2022-10-26 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Certificaat type')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisatie', models.CharField(max_length=100, verbose_name='Organisatie')),
                ('name', models.CharField(max_length=100, verbose_name='Contactpersoon')),
                ('adres', models.CharField(blank=True, max_length=100, verbose_name='Adres')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('plaats', models.CharField(blank=True, max_length=100, verbose_name='Plaats')),
                ('telefoon', models.CharField(max_length=25, verbose_name='Telefoon')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the contact record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, help_text='End date of the contact record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date when the contact was registered in the system')),
            ],
            options={
                'verbose_name_plural': 'Contacten',
            },
        ),
        migrations.CreateModel(
            name='Domein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, verbose_name='URL (SLD.TLD)')),
                ('website', models.BooleanField(default=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('opmerkingen', models.TextField(blank=True, verbose_name='Opmerkingen')),
                ('dnsipv4', models.CharField(blank=True, max_length=100, null=True, verbose_name='DNS record IPv4')),
                ('dnsipv6', models.CharField(blank=True, max_length=100, null=True, verbose_name='DNS record IPv6')),
                ('http', models.BooleanField(default=False, verbose_name='http')),
                ('https', models.BooleanField(default=False, verbose_name='https')),
                ('dnssec', models.BooleanField(default=False, verbose_name='dnssec')),
                ('spf', models.BooleanField(default=False, verbose_name='spf')),
                ('dmarc', models.BooleanField(default=False, verbose_name='dmarc')),
                ('sts', models.BooleanField(default=False, verbose_name='sts')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Domein Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Domein End')),
                ('slug', models.SlugField(default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the domein record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the domein record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date when the Domein was registered in the system')),
                ('betrokkenen', models.ManyToManyField(blank=True, related_name='domeinen', to='domeinen.contact')),
            ],
            options={
                'verbose_name_plural': 'domeinen',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100, verbose_name='Contact Rol')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the rol record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the rol record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date when the rol was registered in the system')),
            ],
            options={
                'verbose_name_plural': 'rollen',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Servernaam')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True)),
            ],
            options={
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Subdomein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Subdomain')),
                ('website', models.BooleanField(default=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Toelichting')),
                ('opmerkingen', models.TextField(blank=True, verbose_name='Opmerkingen')),
                ('dnsipv4', models.CharField(blank=True, max_length=100, null=True, verbose_name='DNS record IPv4')),
                ('dnsipv6', models.CharField(blank=True, max_length=100, null=True, verbose_name='DNS record IPv6')),
                ('http', models.BooleanField(default=False, verbose_name='http')),
                ('https', models.BooleanField(default=False, verbose_name='https')),
                ('dnssec', models.BooleanField(default=False, verbose_name='dnssec')),
                ('spf', models.BooleanField(default=False, verbose_name='spf')),
                ('dmarc', models.BooleanField(default=False, verbose_name='dmarc')),
                ('sts', models.BooleanField(default=False, verbose_name='sts')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Subdomein Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Subdomein End')),
                ('slug', models.SlugField(default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the subdomein record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the subdomein record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date when the Subdomein was registered in the system')),
                ('betrokkenen', models.ManyToManyField(blank=True, related_name='subdomeinen', to='domeinen.contact')),
                ('domein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdomeinen', to='domeinen.domein')),
            ],
            options={
                'verbose_name_plural': 'subdomeinen',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Servicenaam')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='domeinen.server')),
            ],
            options={
                'ordering': ['naam', 'server'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacten', to='domeinen.rol'),
        ),
        migrations.CreateModel(
            name='Certificaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Certificaatnaam')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('opmerkingen', models.TextField(blank=True, verbose_name='Opmerkingen')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Certificaat Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Certificaat End')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the certificaat record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the certificaat record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date when the certificaat was registered in the system')),
                ('betrokkenen', models.ManyToManyField(blank=True, related_name='certificaten', to='domeinen.contact')),
                ('domeinen', models.ManyToManyField(blank=True, related_name='certificaten', to='domeinen.domein')),
                ('servers', models.ManyToManyField(blank=True, related_name='certificaten', to='domeinen.server')),
                ('services', models.ManyToManyField(blank=True, related_name='certificaten', to='domeinen.service')),
                ('subdomeinen', models.ManyToManyField(blank=True, related_name='certificaten', to='domeinen.subdomein')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaten', to='domeinen.certificaattype')),
            ],
            options={
                'verbose_name_plural': 'certificaten',
                'ordering': ['name'],
            },
        ),
    ]
